### ISSUE TITLE
请问运行环境、运行步骤、运行结果可以麻烦记录一下吗？想学习一下

### ISSUE THREAD

**Issue by BinchaoPeng** [litongxin666/pedestrain-attribute#1]

**Comment by BinchaoPeng** [comment]
D:\Program_ML\anaconda3\python.exe C:/Users/PBC/Desktop/pytorch/projects/pedestrain-attribute-master/demo.py
Traceback (most recent call last):
  File "C:/Users/PBC/Desktop/pytorch/projects/pedestrain-attribute-master/demo.py", line 18, in <module>
    image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x)) for x in ['gallery', 'query']}
  File "C:/Users/PBC/Desktop/pytorch/projects/pedestrain-attribute-master/demo.py", line 18, in <dictcomp>
    image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x)) for x in ['gallery', 'query']}
  File "D:\Program_ML\anaconda3\lib\site-packages\torchvision\datasets\folder.py", line 209, in __init__
    is_valid_file=is_valid_file)
  File "D:\Program_ML\anaconda3\lib\site-packages\torchvision\datasets\folder.py", line 93, in __init__
    classes, class_to_idx = self._find_classes(self.root)
  File "D:\Program_ML\anaconda3\lib\site-packages\torchvision\datasets\folder.py", line 122, in _find_classes
    classes = [d.name for d in os.scandir(dir) if d.is_dir()]
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '/home/litongxin/Market-1501/pytorch\\gallery'
